FROM golang:1.23.2-alpine

COPY . . 

RUN go get -d -v

RUN go build -o /app/cmd/cowsay

CMD [ "/app/cmd/cowsay" ]


# Innehåller instruktioner för att skapa en Container Image 
# ta en tom windows 


# Ladda ner java version 8 

# ta min zip-fil och kopiera in den i container image

# kör container image. 

